### ISSUE TITLE
Add a slash command

### ISSUE THREAD

**Issue by rastapopougros** [mattermost/mattermost-plugin-jitsi#11]
The menu entry starts a Jitsi meeting with a random name. That's ok for a quick start in one click.

Suggestion : the plugin could add a slash command with more options, at least to customize the name.

So we could type : 
> /jitsi myname

And the Jitsi Bot would display an invitation for the call `[configured server]/myname`

**Comment by emresaracoglu** [comment]
Definitely

**Comment by ageekhere** [comment]
would be good also to add an option to use a default room name. 
e.g. [configured server]/mainRoom
