### ISSUE TITLE
Radio box for Jitsi Meeting Names has no option set by default

### ISSUE THREAD

**Issue by DHaussermann** [mattermost/mattermost-plugin-jitsi#123]
When you first install and enable the Jitsi plugin and enable it the there is no value set for the radio field `Jitsi Meeting Names`. This is very minor since you can simply set it. Without setting the value, the app seems to behave as though `Random English words in title case (e.g. PlayfulDragonsObserveCuriously)` is set? Users will get this option by default until they update the setting.

![Screen Shot 2020-06-24 at 2 10 04 PM](https://user-images.githubusercontent.com/35588783/85623817-f7329d00-b636-11ea-9757-cf40e524112b.png)

Steps:
- Install and configure Jitsi plugin 
- Enable it
Observed: Jitsi Meeting Names` radio field has no default value

**Comment by jespino** [comment]
@DHaussermann maybe are you using the old config file with the jitsi config settings? we have changed the default key from one option to another, and I removed the whole config section for the jitsi plugin and enabled it again, and now the default setting is there. I think is not a bug, is a problem with old config settings.

**Comment by DHaussermann** [comment]
@jespino it seem's you're correct. On the current master branch with a fresh install, this issue does not occur 

I would suggest we can close this issue.
