### ISSUE TITLE
Add info to admin UI that Embed Jitsi video inside Mattermost and Jitsi Meeting Names do not restrict behavior 

### ISSUE THREAD

**Issue by DHaussermann** [mattermost/mattermost-plugin-jitsi#124]
The admin UI could be a bit more clear that setting an option for `Embed Jitsi video inside Mattermost` and `Jitsi Meeting Names`  is only adjusting preset options for new users. Some admins could get the impression that these options are disabling or restricting the behavior of the plugin.

0/5 This feels a bit subjective. Maybe to others it's obvious that you're only manipulating the presets. But adding something like `Default configuration` in the UI may be worth doing.

**Comment by jespino** [comment]
@jasonblais do you mind to take a look to this?

**Comment by jasonblais** [comment]
How's https://github.com/mattermost/mattermost-plugin-jitsi/pull/125 @DHaussermann and @jespino?

**Comment by jespino** [comment]
@jasonblais LGTM :)

**Comment by jasonblais** [comment]
@jespino can you help with permissions for Dylan?

**Comment by jespino** [comment]
@DHaussermann can you try now, I added you as `maintainer` of the repo, I think should grant you permissions for that.

**Comment by DHaussermann** [comment]
Thanks @jespino that solved it 👍
