### ISSUE TITLE
Use the last version of the logo

### ISSUE THREAD

**Issue by jespino** [mattermost/mattermost-plugin-jitsi#126]
The logo used for the bot is an old version. We have to use the newest version (probably the blue one).

**Comment by jasonblais** [comment]
@jespino https://github.com/jitsi/jitsi-meet/blob/master/images/jitsiLogo_square.png might be a good source

**Comment by jespino** [comment]
Done

**Comment by hanzei** [comment]
See https://github.com/mattermost/mattermost-plugin-jitsi/commit/36562894d5a1fac9f9af3d53270f7742cb4fb3ca#r40219866

**Comment by jespino** [comment]
@hanzei Thanks! very good catch, I didn't know it. Now is fixed, and with a better logo version (the one used for the mobile icon).
