### ISSUE TITLE
When setting to small window in mattermost, SENT video quality gets reduced

### ISSUE THREAD

**Issue by mzealey** [mattermost/mattermost-plugin-jitsi#129]
Mattermost Version - latest docker images

Plugin Version - 2.0.0

**Describe the issue**

When using jitsi from within mattermost in the full screen overlay, quality gets SENT at ~1024x550, when i shrink to using the corner overlay the SENT drops to ~300x200. I believe this is a bug and the send quality should stay the same but perhaps the receive quality should get lowered.

**Comment by jespino** [comment]
Yes, totally agree, the intention was to reduce the receive video quality instead of the sent video quality, I'll take a look into this and I think we can create a 2.0.1 release for that. Thanks for the feedback.

**Comment by jespino** [comment]
Now I see it, the video quality for receive/sent is set in the same call in the Jitsi external API, so is not possible to set the input video quality without setting the output video quality to the same value (from the external API perspective) I think the most sensible approach is to remove that change, and talk with Jitsi people to see if they can split that in the API or any other solution.

**Comment by jespino** [comment]
This is now fixed on master.

**Comment by mzealey** [comment]
thanks, I have raised an issue in jitsi repository above
