### ISSUE TITLE
Jitsi Shortcuts don't work in embedded mode

### ISSUE THREAD

**Issue by hanzei** [mattermost/mattermost-plugin-jitsi#130]
**Mattermost Version**
5.24.0
**Plugin Version**
v2.0.0
**Describe the issue**
When a meeting is open in embedded mode the Jitsi keyboard shortcuts like `c` to open the chat don't work.

**Server Error Logs**
None
**Google Chrome Error Logs**
None
**Screenshots**
N/A

**Additional context**
N/A

**Comment by jespino** [comment]
It was working for me when was focused, for example the m shortcut for mute in the desktop app.

**Comment by jespino** [comment]
I tested in community with the desktop-app, and it works for me (but needs to have the focus on the jitsi window). I going to verify it in chrome.

**Comment by hanzei** [comment]
My bad, focusing the Jitsi screen enabled the shortcuts.
