### ISSUE TITLE
Option to make the embedded view larger

### ISSUE THREAD

**Issue by Centzilius** [mattermost/mattermost-plugin-jitsi#133]
**Mattermost Version**
5.24.2
**Plugin Version**
2.0.0
**Describe the issue**
The embedded view is a bit small for some elements and most things are too large for the default size window (might be related to custom jitsi server). Especially our jitsi server asks to log in if nobody is in the room and that is way too small. It would be great to adjust the size in the server/user config.

**Screenshots**
Generall seems everything a bit too large:
![image](https://user-images.githubusercontent.com/1499392/86604026-1faa8780-bfa5-11ea-8b5c-66b3e1294cb8.png)
Not really visible dialog:
![image](https://user-images.githubusercontent.com/1499392/86604039-23d6a500-bfa5-11ea-84d5-3eba02893732.png)
What the dialog is supposed to look like (if you maximize it)
![image](https://user-images.githubusercontent.com/1499392/86604201-5d0f1500-bfa5-11ea-8f95-454a246062b5.png)
It says something like:
The conference $conference has not been started. If you are the organizer you can log in. Otherwise please wait for the organizer.

**Comment by jespino** [comment]
Yes, we can increase the size of the minimized view a bit, and probably it can help with this kind of messages, but our goal is to include in Jitsi itself a "minimized" mode view, that show things in the right way, hiding certain things, showing others in smaller size (like the icons or the jitsi logo) and probably optimizing the send/receive video quality knowing that is minimized.

@jasonblais What do you think about it, should we go ahead and give it some extra pixels now, or should we wait until Jitsi includes the minimized mode?

**Comment by jasonblais** [comment]
@Centzilius Thanks for the feedback!

@jespino I'm okay increasing the pixels a little until Jitsi includes the minimized mode? We could make it the width of the RHS, if that's enough space? 

![image](https://user-images.githubusercontent.com/13119842/86610926-fcb7ad80-bf7b-11ea-9975-ec3dba514f82.png)

**Comment by jespino** [comment]
I changed it from 320x240 to 384x288 (same proportion, but now is more adjusted to the RHS on mid-size screen (big size screen is even wider the RHS). I think that 64x48 extra pixels perfectly can do the trick with this problem. @Centzilius do you mind to try it?

**Comment by jespino** [comment]
The changes are already on the master branch.

**Comment by Centzilius** [comment]
It's better although the dialog is kind of cut off for some reason but acceptable.
![image](https://user-images.githubusercontent.com/1499392/86617126-17f3de80-bfb7-11ea-934c-0aaf60a6c424.png)
![image](https://user-images.githubusercontent.com/1499392/86617192-3063f900-bfb7-11ea-8d2d-6b79d63eb9e5.png)

**Comment by larkox** [comment]
@jasonblais Should we mark this issue as solved, or do we want to look for other solutions?

**Comment by jasonblais** [comment]
We can close this particular issue, but it would be good to improve the UI of the minimized view. I would defer to @aaronrothschild on its priority though.

Curious if the plugin uses a version of Jitsi that contains the changes Jesús submitted?

**Comment by larkox** [comment]
@jasonblais after double checking, it seems that it is not, and there are a few other minor improvements ready. @aaronrothschild Should we consider a release? Probably v2.0.1.

**Comment by aaronrothschild** [comment]
Yes, let's plan to release it in February after the plugins we are trying
to get published are done, etc.
