### ISSUE TITLE
Jitsi-Plugin v2.0.0 doesn´t start

### ISSUE THREAD

**Issue by DVTrast** [mattermost/mattermost-plugin-jitsi#137]
**Mattermost Version: 5.24.2**

**Jitsti-Plugin Version: 2.0.0**

**Describe the issue**
When I upload the tar.gz file and enable the jitsi plugin, I got the following error:
failed to ensure jitsi bot user.: failed to set profile image: SetProfileImage: Couldn't upload profile image.
I checked the user´s in the mysql database - the jitsi user is in there. The profile image is also in the directory of the user at the mattermost server.

**Server Error Logs**
{"level":"error","ts":1593668650.9586432,"caller":"mlog/log.go:175","msg":"Unable to activate plugin","plugin_id":"jitsi","error":"failed to ensure jitsi bot user.: failed to set profile image: SetProfileImage: Couldn't upload profile image., "}

**Additional context**
The jitsi plugin with the version v1.3.0 is working well.

**Comment by jespino** [comment]
Looks like the plugin is not able to set your bot user profile image, can you verify if you are able to manually set your user profile image? Can be something related to permission in your filesystem or configuration of your S3 bucket.

**Comment by DVTrast** [comment]
Thank you for your answer. I´m able to change my profile image. Do you have any other idea?

**Comment by jespino** [comment]
Looks like a permission problem with the filesystem or something like that. The plugin is trying to write the profile image for the bot but is not being able to do it. Can you ensure that all the permissions of all the files on the mattermost directory? Are you using S3/Minio?

**Comment by DVTrast** [comment]
We found the problem: the file /opt/mattermost/data/users/cbyau6cxhb83mcs7rbrk54a5sc/profile.png belonged root.
Thank you for your help.
