### ISSUE TITLE
Set users to Do Not Disturb when in jitsi

### ISSUE THREAD

**Issue by setpill** [mattermost/mattermost-plugin-jitsi#143]
It would be nice for users' status to be changed while they are in a jitsi meeting via this plugin. Perhaps if they use the embedded view?

**Comment by jespino** [comment]
Yes, it sounds really interesting, what do you think @aaronrothschild?

**Comment by jespino** [comment]
Probably it should be configurable.

**Comment by hanzei** [comment]
Should use custom status: https://github.com/mattermost/mattermost-plugin-jitsi/issues/188
