### ISSUE TITLE
Telemetry: Report if plugin uses a server value other than default (meet.jit.si) 

### ISSUE THREAD

**Issue by aaronrothschild** [mattermost/mattermost-plugin-jitsi#151]
Froma product perspective, I would like to better understand how many people use their own jitsi infrastructure vs the public server out of the box.

**Comment by larkox** [comment]
The idea here is to use the [telemetry package](https://github.com/mattermost/mattermost-plugin-api/tree/master/experimental/telemetry) to add this telemetry.
