### ISSUE TITLE
jwt

### ISSUE THREAD

**Issue by eyebank** [mattermost/mattermost-plugin-jitsi#161]
decided against using the public jitsi server. our installation functions mattermost, however id like use jwt tokens and have failed numerous times.

is there a specific jwt walkthrough for MM users with on-prem jitsi server? if so, please share.

**Comment by jespino** [comment]
Actually, not specific for Mattermost. In mattermost you only have to set the jwt information to match the information of your JWT in Jitsi. In theory this is the documentation to make it work https://github.com/jitsi/lib-jitsi-meet/blob/master/doc/tokens.md

But is not an easy task, have some requirements on lua libraries that are a bit unmaintain, so... It is tricky to get correctly setup.

**Comment by larkox** [comment]
@eyebank is your question answered? Or are you still having trouble?
