### ISSUE TITLE
Allow to overwrite pre join page inside Mattermost

### ISSUE THREAD

**Issue by olivierlambert** [mattermost/mattermost-plugin-jitsi#170]
With Jitsi, you can add a "Pre join page", very useful to let people decide about the webcam/microphone enabled or not.

If you enable this in Jitsi, then the Mattermost small overlay window is too small to be able to read it. But I think an easy way would be to add a checkbox in the plugin to overload the Jitsi server config, like this:

```
const options = {
....
configOverwrite: { prejoinPageEnabled: false }
...
```

This way, people on Mattermost won't have this pre join (if they checked the box), but external people will.

**Comment by larkox** [comment]
@aaronrothschild thoughts on this?

**Comment by aaronrothschild** [comment]
> @aaronrothschild thoughts on this?

I like this idea, makes sense and is good how it treats MM users vs External users.  It would get tiring if this screen was shown to internal users.

**Comment by larkox** [comment]
I think this screen in general has some value, since allows you to check everything is working fine before entering the meeting. I wonder if we should make this configurable (either by user or by installation). What do you think?

**Comment by olivierlambert** [comment]
That was exactly my point in my original post :wink:
