### ISSUE TITLE
Cannot install Received invalid response from the server.

### ISSUE THREAD

**Issue by aryoprakarsa** [mattermost/mattermost-plugin-jitsi#175]
**Mattermost Version**
5.30.1

**Plugin Version**
2.0.0

**Describe the issue**
When the plugin are uploaded an error occurred:
`Received invalid response from the server.`.

**Server Error Logs**

**Google Chrome Error Logs**

**Screenshots**
![Screen Shot 2020-12-20 at 03 15 14](https://user-images.githubusercontent.com/30886148/102698685-d196f100-4271-11eb-865b-4e8c8e0e49e7.png)

**Additional context**

**Comment by bill2004158** [comment]
it seems issue related to upload feature, rather than problem of mattermost-plugin-jitsi.
I have meet same issue before. in my case, it is because the max size limitation for http post.
after I changed increase that limitation, then upload works.

**Comment by larkox** [comment]
@bill2004158 is right. I created https://mattermost.atlassian.net/browse/MM-32154 . Since this is a problem with Mattermost and not the plugin, I will close this issue.
