### ISSUE TITLE
Can't Enable/Activate Plugin - No Jitsi app ID was provided

### ISSUE THREAD

**Issue by frakman1** [mattermost/mattermost-plugin-jitsi#179]
**Mattermost Version**
MM_VERSION=5.31.0

**Plugin Version**
Jitsi (jitsi - 2.0.0)

**Describe the issue**
After installing the plugin, When I try to enable the plugin through the Plugin Manager, I get this error:

![image](https://user-images.githubusercontent.com/5826484/108444088-f125a800-7227-11eb-838c-500ef512f0b7.png)

**Server Error Logs**
```
{"level":"error","ts":1613697954.5203447,"caller":"mlog/log.go:232","msg":"Unable to activate plugin","plugin_id":"jitsi","error":"error no Jitsi app ID was provided"}
```
 
It used to work until I upgraded my Free version of Mattermost to Enterprise and lost all my plugins. I reverted to the Free but still couldn't get the plugins to even show up.

Finally, I deleted the contents of the `plugins` and `client/plugins` and restarted the server. The folders magically re-populated with all my plugins. They all work now except for jitsi. I tried to remove and re-intall jitsi but I still get this error.

I tried chowning -R those folders to `mattermost:mattermost` but no change.
@seansackowitz

**Comment by axac** [comment]
i have the same problem. but in a new installation on yunohost

**Comment by frakman1** [comment]
Make sure "Use JWT Authentication for Jitsi" is set to False in the Plugins Settings page.

**Comment by axac** [comment]
@frakman1 thanks. Yes its good. I installed other plugins for test and i have the same problem. I think its my mattermost installation. thank you very much !.

**Comment by hanzei** [comment]
Disabling JWT authentication should resolve the issue. Closing.
