### ISSUE TITLE
Option: Pass Mattermost username as display name in Jitsi Meeting by default

### ISSUE THREAD

**Issue by skin-soc** [mattermost/mattermost-plugin-jitsi#198]
It would be great in the next update of this plugin if you could **pass Mattermost username by default** as display name on Jitsi Meeting when creating a new meeting as described [here](https://community.jitsi.org/t/jitsi-meet-displayname-via-url-param/32281)

meet.jit.si/meeting-refererence#userInfo.displayName="$username"

**Comment by otbutz** [comment]
Sadly, the current implementation is not optional and represents a usability downgrade for us: #280
