### ISSUE TITLE
Upgraded Mattermost to 5.37.1 Jitsi Cam Icon Disappeared

### ISSUE THREAD

**Issue by jimthedj65** [mattermost/mattermost-plugin-jitsi#200]
**Mattermost Version** 5.37.1

**Plugin Version** 2.0.0

**Describe the issue**
after the upgrade of mattermost the jitsi plugin camera icon disappeared /jitsi still works

**Server Error Logs** nothing significant reported n the logs

**Google Chrome Error Logs** no icon present inside the mattermost app or browsers. Developer tools shows an error for jitsi
`index.js:53 Unable to load bundle for plugin jitsi, version 2.0.0
(anonymous) @ index.js:53
/static/plugins/com.mattermost.plugin-channel-export/com.mattermost.plugin-channel-export_a203ecebef7e7210_bundle.js:1 Failed to load resource: the server responded with a status of 404 ()
index.js:3404 [Util] handleError::  error in script loading:: src::  https://chat.XXXXXXXX.co.uk/static/plugins/com.mattermost.plugin-channel-export/com.mattermost.plugin-channel-export_a203ecebef7e7210_bundle.js id:: plugin_com.mattermost.plugin-channel-export
index.js:53 Unable to load bundle for plugin com.mattermost.plugin-channel-export, version 0.2.2
(anonymous) @ index.js:53
/api/v4/users/login:1 Failed to load resource: the server responded with a status of 401 ()`

**Screenshots**
no icon shows as previously

**Additional context**
nothing further to add

**Comment by larkox** [comment]
@jimthedj65 I have tried on my local, and everything seems to work as expected. Any other details you could add that may help debug this?

Have you tried to disable the plugin and enable again? (or disable the channel export plugin, which seems to be the one appearing in the errors)

**Comment by jimthedj65** [comment]
> @jimthedj65 I have tried on my local, and everything seems to work as expected. Any other details you could add that may help debug this?
> 
> Have you tried to disable the plugin and enable again? (or disable the channel export plugin, which seems to be the one appearing in the errors)

I disabled jitsi and noting changed, when I disabled the export plugin and jitsi same time and then enabled again it came back.

please let me know if there is anything else I could provide and thanks for the response, much apprecated.

**Comment by larkox** [comment]
@agarciamontoro Any ideas why the channel export plugin may be giving problems here? If I remember correctly it has a dummy webapp component, but not sure why it is affecting.

**Comment by jimthedj65** [comment]
> @agarciamontoro Any ideas why the channel export plugin may be giving problems here? If I remember correctly it has a dummy webapp component, but not sure why it is affecting.

I had to enable jitsi first then verified it worked and then the export plugin.  I used the mattermost script to upgrade as I am on debian buster build. [https://mattermost.github.io/docs/4443/administration/upgrade-script.html](url)

**Comment by agarciamontoro** [comment]
So, just to make sure: is it working now? I'm not sure I understood what happened after you re-enabled everything.

**Comment by jimthedj65** [comment]
> So, just to make sure: is it working now? I'm not sure I understood what happened after you re-enabled everything.

yes, it worked after you recommended I turn off both plugins, I was just stating what sequence of events got it working.

1. I ran the upgrade script and all was fine
2. the next day the icon disappeared and wouldn't embed the video screen
3. Turning off jitsi plugin solved nothing
4. turning off the two plugins and then turning on first jitsi and then export plugin brought it back.

hope that helps clear it up and yes it is now working with the new version.

**Comment by agarciamontoro** [comment]
Thank you for the clarification, @jimthedj65!

@larkox, should we close this and repone in case it happens again? It seems it's solved now.
