### ISSUE TITLE
meetingID is allways generateRoomWithoutSeparator

### ISSUE THREAD

**Issue by w00dst0ck** [mattermost/mattermost-plugin-jitsi#22]
Many thanks for this plugin.

However, we had to realize that for each meeting a random name is generated. 
Is a special Mattermost version required to use the req.topic? Currently we are using version 5.8.0.

**Comment by laurawadden** [comment]
@w00dst0ck what was your experience setting this up? This project doesn't have updates for at least 11 months, so wondering if everything still works. Thanks in advance.

**Comment by seansackowitz** [comment]
Hey @laurawadden  Yes, this does still work with all of the latest versions of Mattermost.
@w00dst0ck the plugin is currently set up to only have a random name generated. Is the functionality of having the name consistent based on the room name for example, or some other parameter something you would like to see?

**Comment by w00dst0ck** [comment]
@seansackowitz Thanks for the feedback.

Since the use of Jitsi is currently increasing rapidly due to Covid-19, it would be great if the following features were added.

* Prefix for the Jitsi room name to avoid double assignments
* Use of the Mattermost room name as Jitsi  room name
* combination of both features

Best regards
Kai

**Comment by rbdevr** [comment]
Please have the option to use mattermost channel names or random names set in MM system console.

Why close the ticket if its still under analisys?

**Comment by rbdevr** [comment]
How is this coming along? Any progress?
