### ISSUE TITLE
Calls (Beta) Plugin: add continous ringtone for calls

### ISSUE THREAD

**Issue by jagiella** [mattermost/mattermost-plugin-jitsi#233]
**Mattermost Version**
7.1.8 and 7.10 (self-hosted / docker)

**Plugin Version**
0.10.0 BETA and 0.15.1

**Describe the issue**
When starting calls with the Calls-Plugin (not Jitsi) usually nobody joins as people get a single notification which is easily missed. So that makes the whole calls feature (which is awesome by the way!!) useless as everybody has to be contacted by other means (phone) to make them aware of the meeting.

It would be nice to have a continous ringtone notifying everybody in the same channel of the active call(s) until they join or actively mute the ringtone / refuse the call.

**Comment by mickmister** [comment]
Hi @jagiella, thanks for creating this issue. Since this issue is specific to the Calls plugin, can we close this one in the Jitsi plugin repo?

**Comment by jagiella** [comment]
yes of cause, for Jitsi meeting invitations a continous ringing might just not make sense as they tend to emerge most of the times from an already started discussion in the channel anyways. 

It's rather a feature desired for direkt calls.
