### ISSUE TITLE
Add to Plugin Marketplace

### ISSUE THREAD

**Issue by hanzei** [mattermost/mattermost-plugin-jitsi#27]
Hi @seansackowitz,

Congratulation on forking the zoom plugin and becoming more popular with this plugin :wink: 
Given the current high interest in jitsi, this plugin would be a great addition to the Plugin Marketplace. Would you be interested on submitting your plugin? You can find the process [here](https://developers.mattermost.com/extend/plugins/community-plugin-marketplace/).

**Comment by jespino** [comment]
@hanzei can you confirm if this is already done?

**Comment by hanzei** [comment]
@jespino No, the plugin is not yet in the Marketplace. I can take care of that once a new release is cut.

**Comment by jespino** [comment]
@hanzei Great!
