### ISSUE TITLE
Add per user configuration

### ISSUE THREAD

**Issue by jespino** [mattermost/mattermost-plugin-jitsi#53]
Allow the user to configure its own preferences, like kind of channel, or in the future, if he/she wants to open it in a separate window or embedded in the application.

**Comment by aaronrothschild** [comment]
@asaadmahmood Something to consider in future, for example Tabs for bots to set the settings.... :)

**Comment by jespino** [comment]
I would love to have something like "plugin user config" sections, nothing super special, but if I have a plugin have the hability to register a plugin settings component, and show that plugin setting component in the AccountSettings > Plugins > MyPlugin, would be great. That way the user can configure the settings of his plugin without the need of any slash command, and can easy to discover all the personalization that the plugin give to you.

**Comment by jasonblais** [comment]
@jespino Is this for the `Ask me` migration to a user setting? If so, we talked about starting with a slash command like `/jitsi settings` and moving the option out of the server-level config setting.

**Comment by jespino** [comment]
yes, exactly, I was thinking about that. Probably we can have a conversation about changing the slash command, because I think the proper option is tu have "sub-commands", for example `/jitsi meet` is going to generate a new meeting, `/jitsi config` is going to allow you to config your personal settings, and we can expand this with something like `/jitsi schedule 2020-08-23 --repeat weekly` to schedule automatically generated meetings.

**Comment by jespino** [comment]
Added through slash commands, is enough for now, probably we can add a configuration wizard based on the works from @larkox in the calendar plugin.
