### ISSUE TITLE
"/jitsi help" starts a Jitsi meeting with topic "help", instead of giving help for the /jitsi command

### ISSUE THREAD

**Issue by jasonblais** [mattermost/mattermost-plugin-jitsi#60]
This behaviour started after https://github.com/mattermost/mattermost-plugin-jitsi/pull/41, which renamed the slash command to `/jitsi`.

There are a few options:
1. Name the command back to `/meet`. May conflict with other video meeting plugins, also inconsistent with other integrations like [Slack-Jitsi integration](https://jitsi.org/slack/)
2. Require user to type `/jitsi start` or `/jitsi meet` to start a new meeting. Doesn't follow our ["fast" design principle](https://docs.mattermost.com/developer/fx-guidelines.html#fast-obvious-forgiving)
3. Treat "help" as a reserved word that you cannot start a meeting topic with (i.e. `/jitsi help` gives help).

While the third option may not be obvious, I'm leaning towards it since most other plugins use `/XXX help` to display help for the command.

The output for `/jitsi help` becomes more valuable if #53 is implemented as a slash command.

**Comment by jespino** [comment]
Ok, what about this:

1. If you run `/jitsi` is going to create a based on your meetings creation configuration.
2. If you run `/jitsi help` is going to show the help.
3. If you run `/jitsi config` is going to show you the help for the config command`
4. If you run `/jitsi config meeting_name=ask embed=false` is going to config the meeting name generation to ask and the embed to false.
5. If you run `/jitsi config wizard` is going to ask you through slack actions to configure your jitsi.
7. If you run `/jitsi some text` and `some text` doesn't match with any existing command it will create a meeting named `some text`

**Comment by jasonblais** [comment]
I like it, two notes:

a) I'd propose `/jitsi settings` instead of `/jitsi config` because we use "settings" in other slash commands. It's also more clear for the user.
b) We may not need `/jitsi config wizard`. We could open the message attachment when the user types `/jitsi settings`. The attachment can include the help + actions.

**Comment by jespino** [comment]
Done in master branch
