### ISSUE TITLE
Migrate Jitsi plugin to use bot accounts

### ISSUE THREAD

**Issue by jasonblais** [mattermost/mattermost-plugin-jitsi#63]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Plugin: Jitsi" community channel](https://community-release.mattermost.com/core/channels/plugin-jitsi).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/) and our [Plugins Guide](https://developers.mattermost.com/extend/plugins/).

----

Migrate Jitsi plugin to use bot accounts.

For an example, here is a PR that migrated the Demo Plugin to use bot accounts with a helper function https://github.com/mattermost/mattermost-plugin-demo/pull/29

**Comment by jasonblais** [comment]
Discussed with Jesús - by migrating to using bot accounts, the user cannot remove/delete a meeting they may have posted by an accident. This is a limitation in the existing Zoom plugin.

We can migrate to bot accounts when there is a concrete use case for it, such as for scheduling meetings. Closing.

**Comment by hanzei** [comment]
Should a bot account be used for the ephemeral posts the plugin sends to the user?

**Comment by jasonblais** [comment]
We could use a bot for ephemeral messages, yes

**Comment by jespino** [comment]
Yes, very good point

**Comment by nathanaelhoun** [comment]
Hello, I take this one :-)
