### ISSUE TITLE
Plugin not working in sub paths (example.org/mattermost/)

### ISSUE THREAD

**Issue by mozzieongit** [mattermost/mattermost-plugin-jitsi#76]
**Mattermost Version**
5.21.0

**Plugin Version**
1.3.0

**Describe the issue**
The Plugin doesn't work in sub paths.

**Server Error Logs**
None

**Chromium Error Logs** (I replaced my server with {DOMAIN})

jitsi_72139af559ab6c74_bundle.js:1 POST https://{DOMAIN}/plugins/jitsi/api/v1/meetings 404 (Not Found)
R._end @ jitsi_72139af559ab6c74_bundle.js:1
R.end @ jitsi_72139af559ab6c74_bundle.js:1
(anonymous) @ jitsi_72139af559ab6c74_bundle.js:1
l.then @ jitsi_72139af559ab6c74_bundle.js:1

**Additional context**
I host mattermost in a sub path: {DOMAIN}/**mattermost**/
so the POST (shown in Chrome Error Log) should go to https://{DOMAIN}/**mattermost**/plugins/jitsi/api/v1/meetings

**Comment by jespino** [comment]
Thanks for issuing this bug, it is already solved for the next version (1.4), you can try it building the plugin from the master branch or wait until is released, probably it will be soon, maybe the next week.

**Comment by mozzieongit** [comment]
Ok, thanks

**Comment by mozzieongit** [comment]
When will v1.4.0 be released?
I have problems building (docker-make says golangcli-lint not installed | make throws error when testing with npm)
Or could you build it for me?

**Comment by jespino** [comment]
@mozzieongit sorry, I normally use the regular `make dist` I going to test the docker image and script to verify it. and yes, I can build a tar.gz for you, can you send me an email to `jesus@mattermost.com` and I'll reply to you with the file. Anyway, I going to try to fix the docker approach ASAP.

**Comment by jespino** [comment]
@mozzieongit now should be fixed, can you try again?

**Comment by mozzieongit** [comment]
Worked. Thank you
