### ISSUE TITLE
Add i18n support

### ISSUE THREAD

**Issue by jespino** [mattermost/mattermost-plugin-jitsi#78]
Add support for translate the plugin to other languages, probably starting with english and spanish.

**Comment by jasonblais** [comment]
If anyone is interested helping with this enhancement, here is an article on how a Matterpoll plugin is localized in 6 different languages: https://mattermost.com/blog/localizing-matterpoll/

**Comment by jespino** [comment]
Added the frontend part work here #79

**Comment by jespino** [comment]
Done with #79 and #81
