### ISSUE TITLE
Buttons for Enable Camera and Microphone as well as hang-up are not working 

### ISSUE THREAD

**Issue by DHaussermann** [mattermost/mattermost-plugin-jitsi#85]
I am seeing an issue today where the buttons for Enable Microphone, Enable Camera and Hang Up are not working. They seem unresponsive when I click them. 

I have tested this on desktop and browser and with embedded `true` and `false` 

I did not see this issue yesterday. I'm not sure is the build has changed or if something on my user could be causing this. Possibly it's not prompting me to grant permission to my browser to access the mic and camera. 

When I click hang-up I see a JS error in the browser console:
```
conference.js:411 Uncaught (in promise) TypeError: Cannot read property 'disconnect' of undefined
    at Z (conference.js:411)
    at Object.leaveRoomAndDisconnect (conference.js:2836)
    at Object.hangup (conference.js:2814)
    at actions.web.js:49
...
```
![Hang-up](https://user-images.githubusercontent.com/35588783/83923637-a6730700-a750-11ea-926a-8ca79c2dd5b6.PNG)

Steps: 
- Login to https://omnibus-mattermost.dev.spinmint.com
- Create a Jitsi meeting (can use any naming_scheme)
- Click the link to launch the meeting
**Observed**: Once meeting is running the mic, camera, and hang-up buttons do not work.

**Comment by jespino** [comment]
Looks like a problem in Jitsi code/installation, not in mattermost-plugin-jitsi code.

**Comment by DHaussermann** [comment]
FWIW I did not repro this on my local server using the public cloud instance when I build the plugin from `master`

**Comment by jespino** [comment]
Mmmm, that is weird

**Comment by jespino** [comment]
Can you reproduce it using your plugin locally, but using the https://omnibus-jitsi.dev.spinmint.com for jitsi?

**Comment by DHaussermann** [comment]
I have done some smoke testing today and can no longer reproduce this. 
- Tried new incognito session as well
- Tried denied access ti jitsi webapp for my camera and mic 
I can no longer repro this. 

@jespino any thoughts on if we're okay to close this as it is no reproducing on https://omnibus-jitsi.dev.spinmint.com and never reproduced on the public cloud.

**Comment by jespino** [comment]
@DHaussermann yes, I think is perfectly fine, looks like more a temporary problem or some kind of configuration problem.
