### ISSUE TITLE
Meeting ID link will not show if topic does not contain an alpha-numeric character

### ISSUE THREAD

**Issue by DHaussermann** [mattermost/mattermost-plugin-jitsi#88]
There is an edge case where if you create a meeting with a topic that does not contain an alpha-numeric character, no meeting ID link will be generated for the post as special chanters are removed. 

This is very much an edge case and very low impact as the join link is still displayed. We could consider validating the slash command such that "topic" requires an alpha-numeric character.
 
Steps:
- type `/jitsi !!!` and hit enter
 **Observed** No Meeting ID link to show

**Comment by jespino** [comment]
Yes, good catch, clearly we should validate that.

**Comment by jespino** [comment]
Fixed #96
