### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by seansackowitz** [mattermost/mattermost-plugin-jitsi#9]
Documentation should be added, and include images for how to use and configure the plugin.

**Comment by akomakom** [comment]
Indeed... i tried the plugin from the releases page, couldn't get it to work: 
"We could not start a meeting at this time."

It's unclear whether the zoom plugin (which got installed automatically) needs to be enabled (and configured?).   When enabled I get zoom plugin errors in the logs (I don't have a zoom server).

**Comment by etursunbaev** [comment]
Documentation is highly urgent to be updated.
There is no info how to use it.
As @rastapopougros used default Jitsi server worked for me, but how about other video voice chats and UI ?

**Comment by PackElend** [comment]
> This plugin contains both a server and web app portion.

> As @rastapopougros used default Jitsi server

That leaves me also a bit clueless, so I don't need to have separate Jitsi server, do I? What are the hardware requirements are not little
https://community.jitsi.org/t/jitsi-dev-whats-the-hardware-requirements-on-server-side/10054/1
https://www.youtube.com/watch?time_continue=73&v=8KR0AhDZF2A&feature=emb_logo

**Comment by gittigger** [comment]
> That leaves me also a bit clueless, so I don't need to have separate Jitsi server, do I? 

No, if you set the Jitsi Server URL to https://meet.jit.si it uses the service provided by Jitsi themselves, as others have done.
