### ISSUE TITLE
RN Only - Meeting posts with Mattermost naming scheme have broken links on RN

### ISSUE THREAD

**Issue by DHaussermann** [mattermost/mattermost-plugin-jitsi#91]
When a meeting post with naming scheme of mattermost is shown on RN for a Jisti meeting, the full link is shown. The link includes ALL parameters appended to the address. This looks broken. I think the link text is showing up as plain text and the href address has become the link.

Steps:
- Create a meeting with naming scheme of mattermost
- View the meeting post on RN
**Observed**:
![MobileLinks](https://user-images.githubusercontent.com/35588783/83927181-23ef4500-a75a-11ea-8789-7fe352eaa49f.jpg)

Webapp does nor seem affected.

**Comment by jespino** [comment]
Actually, looks like an inconsistency on how mattermost renders the links in RN. I think I can solve the problem, but anyway probably we can file a ticket for RN to render properly this kind of "not-so-well" formed links.
