### ISSUE TITLE
Running mattermost + Jitsi Plugin in a subdir returns 404

### ISSUE THREAD

**Issue by chillenkoetter** [mattermost/mattermost-plugin-jitsi#97]
When running mattermost in a subdir, the jitsi plugin is not working.

Same as described here: https://github.com/mattermost/mattermost-server/issues/14106 and https://github.com/mattermost/mattermost-plugin-zoom/issues/96

**Comment by jespino** [comment]
This is solved in the new plugin version that is going to be released soon.

**Comment by gstlouisgit** [comment]
is this solved?  I have the same issue and its been a while...
