### ISSUE TITLE
Add slash command autocomplete functionality 

### ISSUE THREAD

**Issue by hanzei** [mattermost/mattermost-plugin-jitsi#98]
From 5.24 MM server has a slash command autocomplete functionality feature. An API can be found [here](https://github.com/mattermost/mattermost-server/blob/master/model/command_autocomplete.go#L28)
To implement the feature add `AutocompleteData` struct to the `Command` when registering a slash command.

Similar PRs:
For Todo plugin https://github.com/mattermost/mattermost-plugin-todo/pull/69
For Agenda plugin https://github.com/mattermost/mattermost-plugin-agenda/pull/40

**Comment by nathanaelhoun** [comment]
Hello ! I take this one :-)

**Comment by jespino** [comment]
@nathanaelhoun Awesome! By the way, is important to understand that it only works properly with 5.24, so you maybe need to upgrade the go.mod file to use the 5.24 version that is going to be released tomorrow (I think).

**Comment by nathanaelhoun** [comment]
Thanks for the precision @jespino ! I will work with the `v5.24-rc3` dependency for today, and I will upgrade it to 5.24 tomorrow (can't wait to update my server :grin:)
